print("Hangman Python!")
print("    **** ")
print("    *  * ")
print("     **")
print("    ****")
print("  *  *  *")
print("*    *    *")
print("*    *     *")
print("     *")
print("    *** ")
print("    * * ")
print("   *   *")
print("  *     *")
print(" *       *")
print("*         *")
print(".          .")
print(" ")
